# Reading and Writing

In [1]:
import pandas as pd

In [4]:
# Read CSV fike
df = pd.read_csv('Car.csv')
df

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [5]:
# Also you can use pd.read_excel('Data.xlsx')

# Read Specific Columns

In [6]:
df = pd.read_csv('Car.csv', usecols = ['MODELYEAR', 'MAKE', 'MODEL'])
df.head()

   MODELYEAR   MAKE       MODEL
0       2014  ACURA         ILX
1       2014  ACURA         ILX
2       2014  ACURA  ILX HYBRID
3       2014  ACURA     MDX 4WD
4       2014  ACURA     RDX AWD

# Check File Data

In [7]:
# Number of rows and columns
df.shape

(1067, 3)

In [8]:
# Columnm names
df.columns

Index(['MODELYEAR', 'MAKE', 'MODEL'], dtype='str')

In [10]:
# Data types
df.dtypes

MODELYEAR    int64
MAKE           str
MODEL          str
dtype: object

In [11]:
# Missing values
df.isna().sum()

MODELYEAR    0
MAKE         0
MODEL        0
dtype: int64

# Save as CSV

In [13]:
# Save DataFrame as excel
df.to_excel('test.xlsx')

In [14]:
# Save DataFrame as pickle
df.to_pickle('test.pkl')