# Sting Operations

## Creat DataFrame

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali Ahmadi", "Sara Mohammadi", "Reza Karimi", "Nima Hosseini"],
    "City": ["tehran", "TEHRAN", "Mashhad", "tehran"],
    "Email": [
        "ali@gmail.com",
        "sara@yahoo.com",
        "reza@gmail.com",
        "nima@gmail.com"
    ]
})

df

             Name     City           Email
0      Ali Ahmadi   tehran   ali@gmail.com
1  Sara Mohammadi   TEHRAN  sara@yahoo.com
2     Reza Karimi  Mashhad  reza@gmail.com
3   Nima Hosseini   tehran  nima@gmail.com

## Conveert to Lowercase

In [3]:
df['City'].str.lower()

0     tehran
1     tehran
2    mashhad
3     tehran
Name: City, dtype: str

## Convert to Uppercase

In [4]:
df['Name'].str.upper()

0        ALI AHMADI
1    SARA MOHAMMADI
2       REZA KARIMI
3     NIMA HOSSEINI
Name: Name, dtype: str

## String Lenght

In [5]:
df['Name'].str.len()

0    10
1    14
2    11
3    13
Name: Name, dtype: int64

## Contains

In [6]:
df['Email'].str.contains('gmail')

0     True
1    False
2     True
3     True
Name: Email, dtype: bool

In [7]:
df[df['Email'].str.contains('gmail')]

            Name     City           Email
0     Ali Ahmadi   tehran   ali@gmail.com
2    Reza Karimi  Mashhad  reza@gmail.com
3  Nima Hosseini   tehran  nima@gmail.com

## Replace

In [9]:
df['City'] = df['City'].str.replace('tehran', 'Tehran')
df

             Name     City           Email
0      Ali Ahmadi   Tehran   ali@gmail.com
1  Sara Mohammadi   TEHRAN  sara@yahoo.com
2     Reza Karimi  Mashhad  reza@gmail.com
3   Nima Hosseini   Tehran  nima@gmail.com

## Split

In [10]:
df[['First_Name', 'Last_name']] = df['Name'].str.split(' ', expand = True)
df

             Name     City           Email First_Name  Last_name
0      Ali Ahmadi   Tehran   ali@gmail.com        Ali     Ahmadi
1  Sara Mohammadi   TEHRAN  sara@yahoo.com       Sara  Mohammadi
2     Reza Karimi  Mashhad  reza@gmail.com       Reza     Karimi
3   Nima Hosseini   Tehran  nima@gmail.com       Nima   Hosseini

## Extract

In [11]:
df['Email'].str.extract(r'@(.+)')

           0
0  gmail.com
1  yahoo.com
2  gmail.com
3  gmail.com

In [ ]:
## Split W